ftp:
  password: pwd
  users:
    user_a: pwd

settings:
  snapshot_frequency: 60s

camera_types:
  amcrest:
    return_snapshot: true

files:
  default_ttl: 30d

database:
  dsn: test_data/db/cam.db

log:
  level: debug



