web:
  frontend:
     js: /app/js
     flutter: /app/flutter

ftp:
  password: pwd
  users:
    user_a: pwd

settings:
  snapshot_frequency: 60s

camera_types:
  amcrest:
    return_snapshot: true

files:
  default_ttl: 30d



