
FROM debian:12.0-slim
RUN apt-get update
RUN apt-get install -y -q sqlite3 tzdata ffmpeg 

WORKDIR /app
COPY build/ /app/
COPY backend/config /app/config

CMD [\
    "/app/server/av-server", \
    "--data-dir", "/app/data", \ 
    "--frontend-dir", "/app/flutter/", \
    "--config-dir", "/app/config" \
]