
FROM alpine:3.14
RUN apk update
RUN apk add  tzdata ffmpeg

WORKDIR /app
COPY build/ /app/
COPY backend/config/docker.yaml /app/config/base.yaml
COPY entrypoint.sh /app/entrypoint.sh

# the zip/unzip process doesn't restore +x
RUN chmod +x /app/server/av-server* 

EXPOSE 9000
EXPOSE 2121

ENTRYPOINT [ "/app/entrypoint.sh" ]