
FROM debian:12.0-slim
RUN apt-get update
RUN apt-get install -y -q sqlite3 tzdata ffmpeg 

WORKDIR /app
COPY build/ /app/
COPY backend/config /app/config
COPY entrypoint.sh /app/entrypoint.sh

EXPOSE 9000
EXPOSE 2121

ENTRYPOINT [ "/app/entrypoint.sh" ]