---
openapi: 3.0.2
info:
  title: API Title
  version: '1.0'
servers:
- url: http://0.0.0.0:9000
paths:
  "/api/cameras":
    get:
      summary: Get all cameras
      description: Get all cameras
      operationId: getCameras
      parameters:
        - in: query
          name: latest_snapshot
          description: 'set true to return latest snapshot info'
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Camera"
components:
  schemas:
    Camera:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        host:
          type: string
        last_seen:
          type: string
          format: date-time
        enabled:
          type: boolean
        timezone:
          type: string
        max_file_age_days:
          type: integer
        max_file_total_mb:
          type: integer
        username:
          type: string
        latest_snapshot:
          "$ref": "#/components/schemas/LatestSnapshot"
      required:
        - id
        - name
        - type
        - host
    LatestSnapshot:
      type: object
      properties:
        id:
          type: integer
        camera_id:
          type: integer
        path:
          type: string
        type:
          type: integer
        timestamp:
          type: string
          format: date-time
        duration_seconds:
          type: integer
        length:
          type: integer
      required:
        - id
        - camera_id
        - path
        - type
        - timestamp
        - duration_seconds
        - length
      additionalProperties: false