/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraFile model module.
 * @module model/CameraFile
 * @version 1.0
 */
class CameraFile {
    /**
     * Constructs a new <code>CameraFile</code>.
     * @alias module:model/CameraFile
     * @param id {Number} 
     * @param cameraId {Number} 
     * @param path {String} 
     * @param type {Number} 
     * @param timestamp {Date} 
     * @param durationSeconds {Number} 
     * @param length {Number} 
     */
    constructor(id, cameraId, path, type, timestamp, durationSeconds, length) { 
        
        CameraFile.initialize(this, id, cameraId, path, type, timestamp, durationSeconds, length);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, cameraId, path, type, timestamp, durationSeconds, length) { 
        obj['id'] = id;
        obj['camera_id'] = cameraId;
        obj['path'] = path;
        obj['type'] = type;
        obj['timestamp'] = timestamp;
        obj['duration_seconds'] = durationSeconds;
        obj['length'] = length;
    }

    /**
     * Constructs a <code>CameraFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraFile} obj Optional instance to populate.
     * @return {module:model/CameraFile} The populated <code>CameraFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraFile();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('camera_id')) {
                obj['camera_id'] = ApiClient.convertToType(data['camera_id'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('duration_seconds')) {
                obj['duration_seconds'] = ApiClient.convertToType(data['duration_seconds'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CameraFile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CameraFile</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CameraFile.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }

        return true;
    }


}

CameraFile.RequiredProperties = ["id", "camera_id", "path", "type", "timestamp", "duration_seconds", "length"];

/**
 * @member {Number} id
 */
CameraFile.prototype['id'] = undefined;

/**
 * @member {Number} camera_id
 */
CameraFile.prototype['camera_id'] = undefined;

/**
 * @member {String} path
 */
CameraFile.prototype['path'] = undefined;

/**
 * @member {Number} type
 */
CameraFile.prototype['type'] = undefined;

/**
 * @member {Date} timestamp
 */
CameraFile.prototype['timestamp'] = undefined;

/**
 * @member {Number} duration_seconds
 */
CameraFile.prototype['duration_seconds'] = undefined;

/**
 * @member {Number} length
 */
CameraFile.prototype['length'] = undefined;






export default CameraFile;

