name: mockoon_proxy
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: any
  json_serializable: any
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  shelf_cors_headers: ^0.1.5
  dio: any
  uuid_type: any
  interact: ^2.2.0


dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0
  build_runner: ^2.4.6
  
