/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiTitle);
  }
}(this, function(expect, ApiTitle) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiTitle.Camera();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Camera', function() {
    it('should create an instance of Camera', function() {
      // uncomment below and update the code to test Camera
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be.a(ApiTitle.Camera);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property host (base name: "host")', function() {
      // uncomment below and update the code to test the property host
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property lastSeen (base name: "last_seen")', function() {
      // uncomment below and update the code to test the property lastSeen
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property maxFileAgeDays (base name: "max_file_age_days")', function() {
      // uncomment below and update the code to test the property maxFileAgeDays
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property maxFileTotalMb (base name: "max_file_total_mb")', function() {
      // uncomment below and update the code to test the property maxFileTotalMb
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

    it('should have the property latestSnapshot (base name: "latest_snapshot")', function() {
      // uncomment below and update the code to test the property latestSnapshot
      //var instance = new ApiTitle.Camera();
      //expect(instance).to.be();
    });

  });

}));
