# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

on: 
    push:

    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

    build-server:
      runs-on: ubuntu-latest
      needs: []
      steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make test-backend
      - run: make server
      - run: make server-arm64
      - uses: actions/upload-artifact@master
        with:
          name: server
          path: build/server

    build-web:
          runs-on: ubuntu-latest
          needs: []
          steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v2
            with:
              node-version: 16.x
          - uses: actions/upload-artifact@master
            with:
              name: js
              path: build/js
    

    build-flutter:
        runs-on: ubuntu-latest
        needs: []
        steps:
        - uses: actions/checkout@v3
    
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.0'
            channel: 'stable'

        - name: Build Flutter Web
          run: make flutter-web
    
        - name: Upload Client
          uses: actions/upload-artifact@v3
          with:
            name: flutter-web
            path: build/flutter/

    build-and-push-image:
    
        runs-on: ubuntu-latest
        needs: [build-server, build-flutter]
        permissions:
          contents: read
          packages: write

        steps:
        - uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Download Server
          uses: actions/download-artifact@v3
          with:
            name: server
            path: build/server

        - name: Download Flutter
          uses: actions/download-artifact@v3
          with:
            name: flutter-web
            path: build/flutter

        - name: Download Flutter
          uses: actions/download-artifact@v3
          with:
            name: js
            path: build/js

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
              
        - name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile_build
            platforms: linux/amd64,linux/arm64
            push: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Push Docker image
          uses: docker/build-push-action@v4
          if: github.ref == 'refs/heads/master'
          with:
            context: .
            file: ./Dockerfile_build
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
