# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Flutter

on: [push]

jobs:

  build-flutter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'
        channel: 'stable'
      
    - name: Build Flutter Web
      run: make flutter-web

    - name: Upload Client
      uses: actions/upload-artifact@v3
      with:
        name: flutter-web
        path: build/flutter/
        retention-days: 5


